version: "3"

services:

 mongo:
  image: mongo:3.2
  ports:
   - "27017:27017"
  networks:
   TP2:
    ipv4_address: 10.11.0.2

 phyton:
  image: kidji/tp2
  ports:
   - "5000:5000"
  networks:
   TP2:
    ipv4_address: 10.11.0.3
  environment:
   - DB_URL=10.11.0.2
networks:
 TP2:
  driver: bridge
  ipam:
   config:
    - subnet: 10.11.0.0/8